# config/meta.yml
meta_title: "Bike's Angels save your bike"
meta_description: "Bike's Angels come to you and repairs your bike in Paris in a couple of minutes"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
